#!/bin/bash

set -e

cd $(dirname $0)/..
PACKAGE=./gopath/src/$(<.package)
if [ -L "${PACKAGE}" ]; then
    rm ${PACKAGE}
fi

if [ ! -e "${PACKAGE}" ]; then
    mkdir -p $(dirname ${PACKAGE})
    ln -s $(pwd) ${PACKAGE}
fi

export GOPATH="$(pwd)/Godeps/_workspace:$(pwd)/gopath"

mkdir -p bin
echo Building Reverse Proxy
CGO_ENABLED=0 go build  -o bin/main -ldflags="-w -X"
